### ISSUE TITLE
A map can have multiple finishes

### ISSUE THREAD

**Issue by Miningflo** [The-Coding-Mods/SpeedMapping-Filter#1]
https://github.com/The-Coding-Mods/SpeedMapping-Filter/blob/b89614040d43cbbacbaffe2e52ae4ce0455a1eed/Definitions.cs#L51

A map can have more than 1 finish. Altough only 1 will probably valid for speedmapping. So also check if user didn't add hidden finish

**Comment by vallzy** [comment]
Fixed as of commit https://github.com/The-Coding-Mods/SpeedMapping-Filter/commit/031fe02f0aca89c85d0ba5ae928d891ecd096128.
