### ISSUE TITLE
TODO: check if checkpoints EXACTLY match with template

### ISSUE THREAD

**Issue by Miningflo** [The-Coding-Mods/SpeedMapping-Filter#3]
https://github.com/The-Coding-Mods/SpeedMapping-Filter/blob/b89614040d43cbbacbaffe2e52ae4ce0455a1eed/Definitions.cs#L52

Check if user didn't add extra checkpoints or removed any from the template

**Comment by vallzy** [comment]
Implemented as of 031fe02f0aca89c85d0ba5ae928d891ecd096128
